version: "3.7"
services:
  db:
    image: postgres:15
    container_name: postgres_app
    env_file:
      - .env
    ports:
      - "5452:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/test_app/build/app.sh" ]
    ports:
      - "80:8888"
    depends_on:
      db:
        condition: service_healthy
    restart: always
