version: "3.7"
services:
  db:
    image: postgres:15
    container_name: postgres_app
    command: -p 5452
    expose:
      - 5452
    env_file:
      - .env
    ports:
      - "5452:5452"
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/test_app/build/app.sh"]
    ports:
      - "80:8888"
    depends_on:
      - db